version: "3"
services:

  tests:
    build:
      context: ..
      dockerfile: Chaincase.Tests/Dockerfile
    links:
      - bitcoind
      - postgres
        
volumes:
  postgres_datadir:
  bitcoin_datadir:
