name: build and test
on: [push, pull_request]

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend Docker Image
        run: cd WalletWasabi.SDK && dotnet clean && docker build . && cd ../
      - name: Build And Run Tests
        run: cd Chaincase.Tests && ./run-tests.sh
